language: csharp
solution: Zookit.sln
install:
  - nuget restore Zookit.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Zookit.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Zookit.Tests/bin/Release/Zookit.Tests.dll
notifications:
  slack: thrashingcode:APaL8WuJBKSYjkZYCeOLAAqq
